title: 島の細道

github_username: hiraeisle

[params]
    
    avatar = "IMG_1874.jpg"
    # avatarDescription = "My avatar description"
    favicon = "favicon.ico"
    description = """
        nothing but nonsense
    """
    
